{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "plane.secretName" . }}
  labels:
    {{- include "plane.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.secrets.secretKey | quote }}
  LIVE_SERVER_SECRET_KEY: {{ .Values.secrets.liveServerSecretKey | quote }}
  DATABASE_URL: {{ include "plane.databaseUrl" . | quote }}
  REDIS_URL: {{ include "plane.redisUrl" . | quote }}
  AMQP_URL: {{ include "plane.amqpUrl" . | quote }}
  {{- if .Values.minio.local }}
  AWS_ACCESS_KEY_ID: {{ .Values.minio.accessKey | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.minio.secretKey | quote }}
  {{- else }}
  AWS_ACCESS_KEY_ID: {{ .Values.minio.external.accessKey | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.minio.external.secretKey | quote }}
  {{- end }}
  {{- if .Values.postgres.local }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  {{- end }}
  {{- if .Values.rabbitmq.local }}
  RABBITMQ_PASSWORD: {{ .Values.rabbitmq.password | quote }}
  {{- end }}
{{- end }}
